version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: palengkedle_password
      POSTGRES_DB: palengkedle_db
    ports:
      - "5432:5432"